### ISSUE TITLE
Add to Packagist.org

### ISSUE THREAD

**Issue by ghost** [prawnsalad/Nexmo-PHP-lib#12]
Hi. Would you consider adding this lib to packagist.org please? That way it can be downloaded & managed via Composer.

It's just a matter of creating a composer.json file and then submitting the repo to https://packagist.org

**Comment by silentroach** [comment]
+1

**Comment by davidbarratt** [comment]
Looks like someone already has
https://packagist.org/packages/prawnsalad/nexmo

You'll need to contact Packagist at contact@packagist.org to get it corrected to your own account.

Also, just so everyone knows, you don't have to ask a package maintainer to add their package to packagist, you can simply specify the repository:
https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by ghost** [comment]
Closing. I don't know the status on this. Nor do I use PHP anymore.
